version: '3'
services:
  web:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run RLHI_Data_Generator.py
    volumes:
      - toolkitui:/app/toolkitui
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  worker:
    build: .
    command: celery -A toolkitui.executor.app worker
    volumes:
      - toolkitui:/app/toolkitui
    depends_on:
      - web
      - redis
