version: '3'
services:
  web:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run toolkitui/GATO_Toolkit.py
    env_file:
      - .env
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: celery -A toolkitui.executor.app worker
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
